services:
  webserver:
    image: cybercertif/apache-php-mysql
    platform: linux/amd64
    restart: always
    ports:
      - "9999:80"
    depends_on:
      - db
    volumes:
      - ./myweb:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "7777:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: adadad
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: db_objet
    restart: always
    volumes:
      - ./mydb:/var/lib/mysql
