services:
  webserver:
    image: cybercertif/apache-php-mysql
    restart: always
    ports:
      - "9999:80"
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./myweb:/var/www/html

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "7777:80"
    environment:
      - PMA_HOST=db   
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:8.0  
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=adadad
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./mydb:/var/lib/mysql
